name: Auto-update doxygen-awesome
permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
  - cron: 0 2 * * 1
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/check_doxygen_awesome_version.yml'
      - '.github/create_submodule_update_pr.sh'

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v6
      - name: Open PR if doxygen-awesome outdated.
        run: |

          VERSION=$(doc/doxygen-awesome-css/update_doxygen_awesome.sh "$(mktemp -d)")
          .github/create_submodule_update_pr.sh doxygen-awesome ${VERSION}
